# Generated by Django 4.2.11 on 2024-03-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=50)),
                ('focus_area', models.CharField(max_length=50)),
                ('time_goal', models.IntegerField()),
                ('calorie_goal', models.IntegerField()),
            ],
        ),
    ]
