# Generated by Django 4.2.11 on 2024-03-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
