# Generated by Django 4.2.11 on 2024-03-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_routine_equipment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='equipment',
            new_name='equipments',
        ),
    ]
