# Generated by Django 4.2.11 on 2024-03-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_equipment_routine_equipments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='focus_area',
            field=models.CharField(choices=[('1', 'Upper Body'), ('2', 'Lower Body'), ('3', 'Core'), ('4', 'Cardio'), ('5', 'Flexibility')], default='1', max_length=1),
        ),
    ]
