# Generated by Django 4.2.11 on 2024-03-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_exercise_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(choices=[('A', 'Bench Press'), ('B', 'Biceps Curl'), ('C', 'Boxing'), ('D', 'Bridge'), ('E', 'Burpees'), ('F', 'Crunches'), ('G', 'Curtsy Lunge'), ('H', 'Cycling'), ('I', 'Dancing'), ('J', 'Deadlifts'), ('K', 'Donkey Kicks'), ('L', 'Dumbbell Curl'), ('M', 'Dumbbell Row'), ('N', 'Glute Bridge'), ('O', 'HIIT Workout'), ('P', 'Jump Rope'), ('Q', 'Jumping Jacks'), ('R', 'Lat Pulldown'), ('S', 'Leg Raise'), ('T', 'Lunges'), ('U', 'Mountain Climbers'), ('V', 'Overhead Press'), ('W', 'Pilates'), ('X', 'Planks'), ('Y', 'Pull-Ups'), ('Z', 'Push-Ups'), ('1', 'Reverse Lunge'), ('2', 'Running'), ('3', 'Russian Twist'), ('4', 'Sit-Ups'), ('5', 'Squats'), ('6', 'Step-Ups'), ('7', 'Stretching'), ('8', 'Superman'), ('9', 'Swimming'), ('0', 'Tricep Dips'), ('#', 'Walking'), ('!', 'Yoga')], max_length=1),
        ),
    ]
